- WORKSPACE
- proxy_wasm_api.h
> Add missing header.

- Makefile
> Fix the Makefile for compiling into the local directory.

- proxy_wasm_intrinsics.cc
> Add missing onCreate for root contexts.

- .github/workflows/cpp.yml
> Enable GitHub Actions for envoy-release/** branches.

- toolchain/cc_toolchain_config.bzl
> Reenable LTO which has a huge effect on performance.

- proxy_wasm_api.h
> Add missing <memory> header.

- proxy_wasm_common.h
> Add case default to make gcc happy.

- proxy_wasm_intrinsics.js
> Add missing external.

- proxy_wasm_api.h
> Fix memory leak.

- proxy_wasm_api.h
> Add overloads for vector property paths.

- proxy_wasm_api.h
> Do not auto-close a GrpcStream.

- .github/workflows/cpp.yml
- bazel/wasm/BUILD
- bazel/wasm/wasm.bzl
- example/BUILD
- example/http_wasm_example.cc
Add wasm cc binary rule, as well as a test using the new rule to build the module.
cc @lizan @PiotrSikora 
> Add wasm_cc_binary rule.

- .github/workflows/cpp.yml
> Run GitHub Actions on istio-release/** branches.

- .github/workflows/cpp.yml
> Run GitHub Actions on istio-release/** branches. (#72)

- WORKSPACE
- bazel/dep/BUILD
- bazel/dep/deps.bzl
- bazel/dep/deps_extra.bzl
> Simplify Bazel workspace. (#70)

- bazel/dep/deps.bzl
- bazel/wasm/BUILD
- bazel/wasm/wasm.bzl
- example/BUILD
- example/http_wasm_example.cc
Cherry-pick #68 with a bit modification on js library because emscripten toolchain as of istio 1.8 requires it.
> Add wasm_cc_binary rule. (#68)

- CODEOWNERS
> Add @bianpengyuan to CODEOWNERS.

- BUILD
> Export LICENSE file.

- BUILD
- bazel/dep/deps.bzl
- bazel/dep/deps_extra.bzl
- proxy_wasm_api.h
While there, update protobuf to v3.17.3.
> Fix protobuf dependency.

- CODEOWNERS
> Remove bianpengyuan@ from CODEOWNERS.

- bazel/emsdk.patch
- bazel/repositories.bzl
> Avoid downloading already available NPM modules.
