proxy_wasm_api.h, proxy_wasm_externs.h
=> Fix linking issues.

README.md
After #1 , now we should use `PROXY_WASM_CPP_SDK` instead `DOCKER_SDK`, right....?
Actually by following current README, we cannot build wasm file like below since `Makefile`s use `PROXY_WASM_CPP_SDK` :
```sh
> docker run -v $PWD:/work -w /work  wasmsdk:v2 /build_wasm.sh
Adding directories to PATH:
PATH += /root/emsdk
PATH += /root/emsdk/upstream/emscripten
PATH += /root/emsdk/node/12.9.1_64bit/bin
Setting environment variables:
EMSDK = /root/emsdk
EM_CONFIG = /root/.emscripten
EMSDK_NODE = /root/emsdk/node/12.9.1_64bit/bin/node
make: Nothing to be done for 'all'.
```
=> Replace DOCKER_SDK to PROXY_WASM_CPP_SDK in readme

proxy_wasm_common.h
=> Remove WasmHeaderMapType::GrpcCreateInitialMetadata.

docs/wasm_filter.md, proxy_wasm_api.h, proxy_wasm_externs.h, proxy_wasm_intrinsics.cc
part of the call to create the gRPC stream.
=> Remove onCreateInitialMetadata and move to supplying initial metadata as

proxy_wasm_api.h, proxy_wasm_externs.h, proxy_wasm_intrinsics.js
=> Changes for use of proxy-wasm in envoy-wasm.

BUILD
Extract from #9, this is needed when an outer WORKSPACE is using different version of protobuf, the generated code won't compile around https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/proxy_wasm_intrinsics.pb.h#L28
=> build: not use pre-generated pb.h/cc for bazel build

toolchain/common.sh
Signed-off-by: Lizan Zhou <lizan@tetrate.io>
=> toolchain: make emscripten toolchain work with rules_foreign_cc

BUILD, proxy_wasm_api.h, proxy_wasm_intrinsics.h, proxy_wasm_intrinsics_full.h, proxy_wasm_intrinsics_lite.h
=> Make using varients of protobuf easier.

proxy_wasm_enums.h
This allows WASM proxies to return any of the statuses supported
by native Envoy filters.
Note that this change will break Envoy until two other PRs are committed to the two other repos -- these are coming soon.
Signed-off-by: Gregory Brail <gregbrail@google.com>
=> Add missing statuses to FilterHeadersStatus.

proxy_wasm_api.h
=> Support raw/non-protobuf gRPC.

proxy_wasm_api.h, proxy_wasm_externs.h, proxy_wasm_intrinsics.cc
This adds the same end_of_stream flag to the on_request_headers
and on_response_headers callbacks that Envoy makes for non-WASM filters.
This way it is possible to write a filter that can operate on the
request or response body but still be resilient if no body is present.
This is an incompatible change -- WASM filters will need to be rebuilt with the additional flag on the proxy_on_request_headers and proxy_on_response_headers flags added.
I'll submit the matching PRs for the other two repos once this one is merged.
Signed-off-by: Gregory Brail <gregbrail@google.com>
=> Pass end_of_stream to header callbacks.

README.md
this is a cosmetic change, to have an example that compiles correctly.
=> Fix README example to reflect new API

contrib/proxy_expr.h, docs/wasm_filter.md, proxy_wasm_api.h, proxy_wasm_intrinsics.cc, proxy_wasm_intrinsics.h
=> emove c++14 support in proxy-wasm.

proxy_wasm_api.h
1、fix exportPairs, set ptr with buffer
2、free ptr in sendLocalResponse
=> fix sendLocalResponse unable to update headers

proxy_wasm_intrinsics.cc
=> Bump Proxy-Wasm ABI version to 0.2.0.

proxy_wasm_api.h, proxy_wasm_externs.h, proxy_wasm_intrinsics.js
This lets the WASM code determine the log level set for the
"wasm" logger on the proxy host, which can be used to optimize
when log messages are generated.
Signed-off-by: Gregory Brail <gregbrail@google.com>
=> Add support for proxy_get_log_level

proxy_wasm_intrinsics.cc
This is necessary because the new proxy_get_log_level function
only exists there.
Signed-off-by: Gregory Brail <gregbrail@google.com>
=> Change ABI version to 0.2.1

proxy_wasm_api.h
=> Add include <cstring> for clang-tidy.

proxy_wasm_api.h, proxy_wasm_intrinsics.cc
=> Move onLog to ContextBase since it can be called on a Root Context.

bazel/dep/deps.bzl
Downgrade emscripten to 1.39.6 at istio release 1.8 branch to make it match the tool chain used by istio/envoy 1.8. Somehow modules compiled with 1.39.19 emscripten does not work with istio 1.8.0 release.
=> Downgrade Emscripten to v1.39.6.

README.md
=> Beautify code snippets.

proxy_wasm_api.h
=> Fix memory leak when sending initial metadata in gRPC callouts.

BUILD, proxy_wasm_api.h, proxy_wasm_common.h, proxy_wasm_enums.h, proxy_wasm_externs.h
While there, allow "proxy_wasm_externs.h" externs to be exported
as either C (for Wasm) or C++ (for NullVM).
=> Add missing includes.

.github/workflows/cpp.yml
Fixes issues with addlicense requiring Go v1.16+.
=> Use actions/setup-go@v2 in GitHub Actions.

BUILD, README.md, bazel/dep/deps.bzl, bazel/wasm/wasm.bzl, example/BUILD, sdk_container.sh, toolchain/cc_toolchain_config.bzl, toolchain/emcc.sh
=> Update Emscripten to v3.1.1.

README.md, bazel/dep/deps.bzl, sdk_container.sh, toolchain/cc_toolchain_config.bzl
=> Update Emscripten to v3.1.7.

WORKSPACE, bazel/dependencies.bzl, bazel/dependencies_extra.bzl, bazel/repositories.bzl
Just change the name of bazel functions to use "sdk".
Signed-off-by: Ingwon Song <igsong@google.com>
=> Fix typos in Bazel function names.

proxy_wasm_api.h
proxy_asm_api.h references `std::optional`—see, for example, `getProperty`—but was missing the include for it.
=> Add <optional> include to proxy_asm_api.h.

proxy_wasm_intrinsics.cc
Fixes https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/issues/175
Short term fix for: https://github.com/emscripten-core/emscripten/issues/22782
=> fix: Implement getentropy using wasi preview 1

proxy_wasm_api.h
Added in https://github.com/envoyproxy/envoy/pull/32585.
Required for https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/411
=> build: Upstream envoy's C++20 patch

.github/workflows/cpp.yml
actions/cache@v1 is no longer supported:
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> chore: update build action to use actions/cache@v4
